{
 "title": "BMP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "router_ip",
    "query": "{\"find\": \"terms\", \"field\": \"router_ip.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "経路UPDATE/WITHDRAWN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "UPDATE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action.keyword: add",
     "timeField": "@timestamp"
    },
    {
     "alias": "WITHDRAWN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "4", "type": "count" }
     ],
     "query": "action.keyword: del",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BGP UPDATE Count by Transit ASN (Top 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "transit_asn.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action.keyword: add AND router_ip.keyword: $router_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BGP UPDATE Count by Origin AS (Top 10)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "origin_as.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "action.keyword: add AND router_ip.keyword: $router_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "経路UPDATE/WITHDRAW",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "(action.keyword: add OR action.keyword: del)\nAND router_ip.keyword: $router_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BGPピア UP/DOWN ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "action.keyword: up OR action.keyword: down",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}